name: Build & Push (Quay) - Keycloak

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'docker/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag da imagem (ex: dev, uat, prd, v1.0.0)'
        required: false
        default: 'dev'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      REGISTRY: quay.io
      ORG: ${{ secrets.QUAY_ORG }}
      IMAGE_NAME: rhbk-keycloak-custom
      CONTEXT_DIR: docker
      TAG: ${{ github.event.inputs.tag || (startsWith(github.ref, 'refs/tags/') && github.ref_name) || github.ref_name || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Buildx ok, mas vamos fixar driver e evitar variações
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Validate variables
        run: |
          if [ -z "${ORG}" ]; then
            echo "ERROR: QUAY_ORG is empty. Configure secrets.QUAY_ORG with your Quay namespace (ex: thiagobotelho)."
            exit 1
          fi
          echo "Image: ${REGISTRY}/${ORG}/${IMAGE_NAME}:${TAG}"

      - name: Login registry.redhat.io
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHDN_USERNAME }}
          password: ${{ secrets.RHDN_PASSWORD }}

      - name: Login Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build & Push (single-manifest, docker v2s2)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          file: ${{ env.CONTEXT_DIR }}/Dockerfile
          push: true

          # single-arch
          platforms: linux/amd64

          tags: |
            ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

          # força mediatypes Docker (evita OCI index "See Child Manifests")
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }},push=true,oci-mediatypes=false

          # reduz metadata extra no manifest
          provenance: false
          sbom: false

          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
